# Linux / macOS 环境

name: genescreen
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - blast>=2.12
  - ripgrep>=14
  - cairosvg           # LINKVIEW 依赖，SVG 转 PNG
  - pip:
    - pyfaidx
    - biopython
